name: Daily Reindex

on:
  schedule:
    - cron: '0 3 * * *'  # daily at 3:00 AM UTC
  workflow_dispatch:      # manual trigger still available

jobs:
  curl-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call reindex endpoint and show output
        run: |
          echo "Calling reindex endpoint..."
          curl -i https://ai-powered-fitment-search-eijmn.ondigitalocean.app/reindex
