name: Frequent Reindex

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  curl-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call reindex endpoint and show output
        run: |
          echo "Calling reindex endpoint..."
          curl -i https://ai-powered-fitment-search-eijmn.ondigitalocean.app/reindex
